TEST_SITE_URL = 'https://demo.guru99.com/telecom/index.html'
MAX_WAIT_INTERVAL = 5


VALID_FIRST_NAME = "Madi"
VALID_LAST_NAME = "XYZ"
VALID_EMAIL = "madi@gmail.com"
VALID_ADDRESS = "30 Hudson St"
VALID_TEL_NUMBER = "1234567891"

NUMBER_NAME = "123ABC"
SPECIAL_CHARAC_NAME = '!@SHKF'
INVALID_EMAIL ='ksdj@f123'
INVALID_ADDRESS = "!$wkjhf"
LETTER_TEL = 'F12342'
SPECIAL_CHARAC_TEL = '!23455'

VALID_MONTHLY_RENTAL = 25
VALID_FREE_LOCAL_MINUTES = 200
VALID_FREE_INTERNATIONAL_MINUTES = 100
VALID_FREE_SMS_PACK = 300
VALID_LOCAL_PER_MIN_CHARGE = 2
VALID_INTERNATIONAL_PER_MIN_CHARGE = 5
VALID_SMS_PER_CHARGE = 1


APPROVED_MONTHLY_RENTAL = 500
APPROVED_FREE_LOCAL_MINUTES = 200
APPROVED_FREE_INTERNATIONAL_MINUTES = 100
APPROVED_FREE_SMS_PACK = 500
APPROVED_LOCAL_PER_MIN_CHARGE = 3
APPROVED_INTERNATIONAL_PER_MIN_CHARGE = 20
APPROVED_SMS_PER_CHARGE = 4

MADE_UP_CUSTOMER_ID = '111111'
SPECIAL_CHARAC_CUSTOMER_ID = '!$2JF2'
LETTER_CUSTOMER_ID = 'KSJFH2'

ADD_PLAN_CUSTOMER_LOOK_UP_URL = 'https://demo.guru99.com/telecom/assigntariffplantocustomer.php'
PAY_BILLING_CUSTOMER_LOOK_UP_URL = 'https://demo.guru99.com/telecom/billing.php'
